/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.uniska.pbo2.p03;

import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.FlatDarkLaf;
import java.util.ArrayList;

/**
 *
 * @author ASUS
 */
public class FormPendaftaran extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPendaftaran.class.getName());

    /**
     * Creates new form FormPendaftaran
     */
    public FormPendaftaran() {
        initComponents();
        
        namaField.putClientProperty("JTextField.placeholderText", "Nama Lengkap");
        npmField.putClientProperty("JTextField.placeholderText", "Contoh: 2410010001");
        getRootPane().setDefaultButton(daftarButton);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenisKelaminGroup = new javax.swing.ButtonGroup();
        namaLabel = new javax.swing.JLabel();
        npmLabel = new javax.swing.JLabel();
        prodiLabel = new javax.swing.JLabel();
        jenisKelaminLabel = new javax.swing.JLabel();
        minatLabel = new javax.swing.JLabel();
        namaField = new javax.swing.JTextField();
        npmField = new javax.swing.JTextField();
        prodiCombo = new javax.swing.JComboBox<>();
        lakiRadio = new javax.swing.JRadioButton();
        perempuanRadio = new javax.swing.JRadioButton();
        javaCheck = new javax.swing.JCheckBox();
        webCheck = new javax.swing.JCheckBox();
        pythonCheck = new javax.swing.JCheckBox();
        daftarButton = new javax.swing.JButton();
        temaToggle = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Pendaftaran Workshop");

        namaLabel.setText("Nama");
        namaLabel.setName("namaLabel"); // NOI18N

        npmLabel.setText("NPM");
        npmLabel.setName("npmLabel"); // NOI18N

        prodiLabel.setText("Program Studi");
        prodiLabel.setName("prodiLabel"); // NOI18N

        jenisKelaminLabel.setText("Jenis Kelamin");
        jenisKelaminLabel.setName("jenisKelaminLabel"); // NOI18N

        minatLabel.setText("Minat");
        minatLabel.setName("minatLabel"); // NOI18N

        namaField.setName("namaField"); // NOI18N

        npmField.setName("npmField"); // NOI18N

        prodiCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teknik Informatika", "Sistem Informasi", "Manajemen Informatika" }));
        prodiCombo.setName("prodiCombo"); // NOI18N

        jenisKelaminGroup.add(lakiRadio);
        lakiRadio.setSelected(true);
        lakiRadio.setText("Laki-laki");

        jenisKelaminGroup.add(perempuanRadio);
        perempuanRadio.setText("Perempuan");

        javaCheck.setText("Java");
        javaCheck.setName("javaCheck"); // NOI18N

        webCheck.setText("Web");
        webCheck.setName("pythonJava"); // NOI18N

        pythonCheck.setText("Python");
        pythonCheck.setName("pythonJava"); // NOI18N

        daftarButton.setText("Daftar");
        daftarButton.addActionListener(this::daftarButtonActionPerformed);

        temaToggle.setText("Mode Gelap");
        temaToggle.addActionListener(this::temaToggleActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(minatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namaLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(npmLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prodiLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jenisKelaminLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(npmField)
                            .addComponent(namaField)
                            .addComponent(lakiRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(perempuanRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(prodiCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(76, 76, 76))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(javaCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pythonCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(webCheck)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(temaToggle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(daftarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npmLabel)
                    .addComponent(npmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodiLabel)
                    .addComponent(prodiCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisKelaminLabel)
                    .addComponent(lakiRadio))
                .addGap(3, 3, 3)
                .addComponent(perempuanRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minatLabel)
                    .addComponent(javaCheck)
                    .addComponent(webCheck)
                    .addComponent(pythonCheck))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daftarButton)
                    .addComponent(temaToggle))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void daftarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarButtonActionPerformed
        // TODO add your handling code here:
        tampilkanRingkasan();
    }//GEN-LAST:event_daftarButtonActionPerformed

    private void temaToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temaToggleActionPerformed
        // TODO add your handling code here:
        gantiTema(temaToggle.isSelected());
    }//GEN-LAST:event_temaToggleActionPerformed

    /**
     * @param args the command line arguments
     */
    private void tampilkanRingkasan() {
        String jenisKelamin = lakiRadio.isSelected() ? "Laki-laki" : "Perempuan";
        
        List<String> minat = new ArrayList<>();
        for (JCheckBox cb : List.of(javaCheck, pythonCheck, webCheck)) {
            if (cb.isSelected()) {
                minat.add(cb.getText());
            }
        }
        
        String pesan = "Nama: " + namaField.getText()
                + "\nNPM: " + npmField.getText()
                + "\nProgram Studi: " + prodiCombo.getSelectedItem()
                + "\nJenis Kelamin: " + jenisKelamin
                + "\nMinat: " + (minat.isEmpty() ? "-" : String.join(", ", minat));
        
        JOptionPane.showMessageDialog(this, pesan, "Data Pendaftaran", 
                JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void gantiTema(boolean gelap) {
        if (gelap) {
            FlatDarkLaf.setup();
        } else {
            FlatLightLaf.setup();
        }
        FlatLaf.updateUI();
        temaToggle.setText(gelap ? "Mode Terang" : "Mode Gelap");
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPendaftaran().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton daftarButton;
    private javax.swing.JCheckBox javaCheck;
    private javax.swing.ButtonGroup jenisKelaminGroup;
    private javax.swing.JLabel jenisKelaminLabel;
    private javax.swing.JRadioButton lakiRadio;
    private javax.swing.JLabel minatLabel;
    private javax.swing.JTextField namaField;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JTextField npmField;
    private javax.swing.JLabel npmLabel;
    private javax.swing.JRadioButton perempuanRadio;
    private javax.swing.JComboBox<String> prodiCombo;
    private javax.swing.JLabel prodiLabel;
    private javax.swing.JCheckBox pythonCheck;
    private javax.swing.JToggleButton temaToggle;
    private javax.swing.JCheckBox webCheck;
    // End of variables declaration//GEN-END:variables
}
